// frontend/src/components/ui/ComplianceDisclaimer.js
// Reusable compliance disclaimer component for regulatory requirements

import React from 'react';
import PropTypes from 'prop-types';
import { AlertTriangle, Info, Bot } from '../icons';
import './ComplianceDisclaimer.css';

/**
 * ComplianceDisclaimer Component
 *
 * Displays regulatory disclaimers in various formats for compliance with
 * German/Austrian financial services law (BaFin/FMA) and MiFID II.
 *
 * @param {string} variant - Display variant: 'inline', 'banner', 'compact', 'ai-label'
 * @param {string} type - Disclaimer type: 'general', 'ai', 'simulation', 'backtest', 'analysis'
 * @param {string} className - Additional CSS classes
 */
const ComplianceDisclaimer = ({ variant = 'inline', type = 'general', className = '' }) => {
  const disclaimerContent = {
    general: {
      icon: AlertTriangle,
      title: 'Important Notice',
      text: 'For educational purposes only. Not investment advice. Always consult qualified professionals before making investment decisions.',
      shortText: 'Educational purposes only. Not investment advice.'
    },
    ai: {
      icon: Bot,
      title: 'AI-Generated Analysis',
      text: 'This analysis is generated by AI and may contain errors. AI systems can produce incorrect outputs and lack context about recent events. Never rely solely on AI-generated insights for investment decisions.',
      shortText: 'AI-generated. May contain errors.'
    },
    simulation: {
      icon: Info,
      title: 'Paper Trading Only',
      text: 'This is a simulation using virtual funds. No real money is involved. Simulated results do not reflect actual trading performance and should not be used to predict real trading outcomes.',
      shortText: 'Simulated trading. No real money.'
    },
    backtest: {
      icon: AlertTriangle,
      title: 'Hypothetical Results',
      text: 'These are backtested/hypothetical results that do not represent actual trading. Past performance is not indicative of future results. Backtested results have inherent limitations including survivorship bias.',
      shortText: 'Hypothetical results. Past performance ≠ future results.'
    },
    analysis: {
      icon: Info,
      title: 'Informational Only',
      text: 'This analysis is for informational purposes only and does not constitute a recommendation to buy or sell any security. Always do your own research.',
      shortText: 'Informational only. Do your own research.'
    }
  };

  const content = disclaimerContent[type] || disclaimerContent.general;
  const IconComponent = content.icon;

  // AI Label - minimal badge style
  if (variant === 'ai-label') {
    return (
      <span className={`compliance-disclaimer compliance-disclaimer--ai-label ${className}`}>
        <Bot size={12} />
        <span>AI-Generated</span>
      </span>
    );
  }

  // Compact - single line
  if (variant === 'compact') {
    return (
      <div className={`compliance-disclaimer compliance-disclaimer--compact compliance-disclaimer--${type} ${className}`}>
        <IconComponent size={14} />
        <span>{content.shortText}</span>
      </div>
    );
  }

  // Banner - prominent top banner
  if (variant === 'banner') {
    return (
      <div className={`compliance-disclaimer compliance-disclaimer--banner compliance-disclaimer--${type} ${className}`}>
        <div className="compliance-disclaimer__icon">
          <IconComponent size={20} />
        </div>
        <div className="compliance-disclaimer__content">
          <strong className="compliance-disclaimer__title">{content.title}</strong>
          <p className="compliance-disclaimer__text">{content.text}</p>
        </div>
      </div>
    );
  }

  // Default: Inline - subtle footer style
  return (
    <div className={`compliance-disclaimer compliance-disclaimer--inline compliance-disclaimer--${type} ${className}`}>
      <IconComponent size={12} />
      <span>{content.shortText}</span>
    </div>
  );
};

ComplianceDisclaimer.propTypes = {
  variant: PropTypes.oneOf(['inline', 'banner', 'compact', 'ai-label']),
  type: PropTypes.oneOf(['general', 'ai', 'simulation', 'backtest', 'analysis']),
  className: PropTypes.string
};

export default ComplianceDisclaimer;
